server:
    port: 80

spring:
    datasource:
        driver-class-name: org.h2.Driver
        url: jdbc:h2:mem:sample
        usename: sa
        password:
    h2:
        console:
            enabled: true
            path: /sample
    jpa:
        hibernate:
            ddl-auto: create
        show-sql: true